// Command genserverlist regenerates the compiled-in IANA tables in
// internal/serverlist: the RDAP bootstrap baseline (rdap_servers.go) and the
// WHOIS server map (whois_servers.go).
//
// Both files are mirrors of what IANA publishes at the moment of the run.
// An entry IANA no longer reports is dropped, never kept: a table that keeps
// its own entries is no longer a mirror, and the drift it hides is exactly
// what regenerating is supposed to surface. Conversely, nothing is written
// unless every fetch and every lookup succeeded, so a network failure can
// never be mistaken for a registry withdrawing its server.
//
// The RDAP baseline is derived through serverlist.FetchIANA — the same code
// path the running service uses to refresh itself — so the compiled fallback
// and the live data cannot disagree about how a bootstrap file is read.
// Custom RDAP entries (rdap_servers_custom.go) are not generated, but they
// override both the baseline and live IANA data, so a custom entry that IANA
// now publishes itself is reported: it is either redundant, or it is masking
// the registry's own answer, and either way it needs deleting by hand.
//
// Usage:
//
//	go run ./tools/genserverlist [flags]
package main

import (
	"bufio"
	"bytes"
	"context"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/KincaidYang/whois/internal/serverlist"
)

const (
	rootZoneURL     = "https://data.iana.org/TLD/tlds-alpha-by-domain.txt"
	ianaWhoisServer = "whois.iana.org:43"

	// whoisAttempts is how often one TLD's lookup is retried before the whole
	// run is abandoned. IANA answers reliably, but a single dropped connection
	// in ~1500 lookups would otherwise delete a real entry from the table.
	whoisAttempts = 3

	// collisionExitCode reports that the tables were written but a custom RDAP
	// entry now collides with IANA's own data. The caller (the workflow) can
	// still open its pull request and fail afterwards.
	collisionExitCode = 3
)

// generatedHeader marks both outputs as machine-written. They are mirrors:
// a hand-edit survives only until the next run, so corrections belong in
// rdap_servers_custom.go instead.
const generatedHeader = "// Code generated by tools/genserverlist. DO NOT EDIT.\n\n"

const rdapFileHeader = generatedHeader + `package serverlist

// compiledRdapServers is the compiled-in IANA baseline data.
// It is used as a fallback when the live IANA bootstrap fetch fails.
// Source: https://data.iana.org/rdap/
var compiledRdapServers = map[string]string{
`

const whoisFileHeader = generatedHeader + `package serverlist

// TLDToWhoisServer
// This map is used to determine the whois server for a given TLD.
// Source: https://www.iana.org/domains/root/db
var TLDToWhoisServer = map[string]string{
`

// rdapSections are the four bootstrap registries, in the order they appear in
// the generated file. RDAP is looked up by IP address, by ASN and by TLD, and
// each of those answers comes from its own IANA file.
var rdapSections = []struct {
	category string // key used by serverlist.FetchIANA
	title    string
}{
	{"ipv4", "IPv4 RDAP servers"},
	{"ipv6", "IPv6 RDAP servers"},
	{"asn", "ASN RDAP servers"},
	{"dns", "TLD RDAP servers"},
}

func main() {
	dir := flag.String("dir", filepath.Join("internal", "serverlist"), "directory holding the generated files")
	only := flag.String("only", "", `regenerate only "rdap" or "whois" (default: both)`)
	workers := flag.Int("concurrency", 4, "concurrent whois.iana.org lookups")
	summaryPath := flag.String("summary", "", "also write the run summary, as Markdown, to this file")
	timeout := flag.Duration("timeout", 30*time.Minute, "deadline for the whole run")
	flag.Parse()

	if *only != "" && *only != "rdap" && *only != "whois" {
		fmt.Fprintf(os.Stderr, "genserverlist: -only must be %q or %q\n", "rdap", "whois")
		os.Exit(2)
	}
	if *workers < 1 {
		fmt.Fprintln(os.Stderr, "genserverlist: -concurrency must be at least 1")
		os.Exit(2)
	}

	ctx, cancel := context.WithTimeout(context.Background(), *timeout)
	defer cancel()

	var summary strings.Builder
	collisions := false

	if *only != "whois" {
		found, err := generateRDAP(ctx, *dir, &summary)
		if err != nil {
			fail(err)
		}
		collisions = found
	}
	if *only != "rdap" {
		if err := generateWhois(ctx, *dir, *workers, &summary); err != nil {
			fail(err)
		}
	}

	fmt.Print(summary.String())
	if *summaryPath != "" {
		if err := os.WriteFile(*summaryPath, []byte(summary.String()), 0o644); err != nil {
			fail(err)
		}
	}
	if collisions {
		os.Exit(collisionExitCode)
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "genserverlist:", err)
	os.Exit(1)
}

// generateRDAP rewrites rdap_servers.go from the four IANA bootstrap files and
// reports whether any custom entry collides with them.
func generateRDAP(ctx context.Context, dir string, summary *strings.Builder) (collisions bool, err error) {
	client := &http.Client{Timeout: 30 * time.Second}
	perCategory, failed := serverlist.FetchIANA(ctx, client)
	if len(failed) > 0 {
		sort.Strings(failed)
		return false, fmt.Errorf("bootstrap fetch failed for %s: leaving the table untouched", strings.Join(failed, ", "))
	}

	var buf bytes.Buffer
	buf.WriteString(rdapFileHeader)
	fresh := make(map[string]string)
	for i, section := range rdapSections {
		if i > 0 {
			buf.WriteString("\n")
		}
		fmt.Fprintf(&buf, "\t// %s\n", section.title)
		entries := perCategory[section.category]
		for _, key := range sortByURLThenKey(entries) {
			fmt.Fprintf(&buf, "\t%q: %q,\n", key, entries[key])
			fresh[key] = entries[key]
		}
	}
	buf.WriteString("}\n")

	path := filepath.Join(dir, "rdap_servers.go")
	old, err := parseStringMap(path, "compiledRdapServers")
	if err != nil {
		return false, err
	}
	if err := writeGoFile(path, buf.Bytes()); err != nil {
		return false, err
	}
	writeDiff(summary, "rdap_servers.go", old, fresh)

	custom, err := parseStringMap(filepath.Join(dir, "rdap_servers_custom.go"), "customRdapServers")
	if err != nil {
		return false, err
	}
	return writeCollisions(summary, custom, fresh), nil
}

// generateWhois rewrites whois_servers.go from the root zone list, asking IANA
// for each TLD's WHOIS server.
func generateWhois(ctx context.Context, dir string, workers int, summary *strings.Builder) error {
	client := &http.Client{Timeout: 30 * time.Second}
	tlds, err := fetchRootZone(ctx, client)
	if err != nil {
		return err
	}

	servers, err := lookupWhoisServers(ctx, tlds, workers)
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	buf.WriteString(whoisFileHeader)
	keys := make([]string, 0, len(servers))
	for key := range servers {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		fmt.Fprintf(&buf, "\t%q: %q,\n", key, servers[key])
	}
	buf.WriteString("}\n")

	path := filepath.Join(dir, "whois_servers.go")
	old, err := parseStringMap(path, "TLDToWhoisServer")
	if err != nil {
		return err
	}
	if err := writeGoFile(path, buf.Bytes()); err != nil {
		return err
	}
	fmt.Fprintf(summary, "Queried %d root-zone TLDs; %d report a WHOIS server.\n\n", len(tlds), len(servers))
	writeDiff(summary, "whois_servers.go", old, servers)
	return nil
}

// fetchRootZone returns every TLD in the root zone, lowercased, in the order
// IANA lists them.
func fetchRootZone(ctx context.Context, client *http.Client) ([]string, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, rootZoneURL, nil)
	if err != nil {
		return nil, err
	}
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("unexpected status %d from %s", resp.StatusCode, rootZoneURL)
	}

	var tlds []string
	scanner := bufio.NewScanner(resp.Body)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		tlds = append(tlds, strings.ToLower(line))
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	if len(tlds) == 0 {
		return nil, fmt.Errorf("%s listed no TLDs", rootZoneURL)
	}
	return tlds, nil
}

// lookupWhoisServers asks IANA for every TLD's WHOIS server, dropping the ones
// with no server. A lookup that keeps failing aborts the run: an unanswered
// query says nothing about whether the registry still runs WHOIS.
func lookupWhoisServers(ctx context.Context, tlds []string, workers int) (map[string]string, error) {
	ctx, cancel := context.WithCancel(ctx)
	defer cancel()

	var (
		mu       sync.Mutex
		servers  = make(map[string]string, len(tlds))
		firstErr error
		wg       sync.WaitGroup
	)
	queue := make(chan string)

	for i := 0; i < workers; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for tld := range queue {
				server, err := lookupWhoisServer(ctx, ianaWhoisServer, tld)
				mu.Lock()
				switch {
				case err != nil:
					if firstErr == nil {
						firstErr = err
						cancel()
					}
				case server != "":
					servers[tld] = server
				}
				mu.Unlock()
			}
		}()
	}

	for _, tld := range tlds {
		select {
		case queue <- tld:
		case <-ctx.Done():
		}
	}
	close(queue)
	wg.Wait()

	if firstErr != nil {
		return nil, fmt.Errorf("WHOIS lookup failed, leaving the table untouched: %w", firstErr)
	}
	return servers, nil
}

// lookupWhoisServer returns the WHOIS server IANA reports for one TLD, or the
// empty string when IANA reports none.
func lookupWhoisServer(ctx context.Context, addr, tld string) (string, error) {
	var lastErr error
	for attempt := 1; attempt <= whoisAttempts; attempt++ {
		if attempt > 1 {
			select {
			case <-time.After(time.Duration(attempt-1) * 2 * time.Second):
			case <-ctx.Done():
				return "", ctx.Err()
			}
		}
		server, err := queryIANA(ctx, addr, tld)
		if err == nil {
			return server, nil
		}
		lastErr = err
	}
	return "", fmt.Errorf("%s: %w", tld, lastErr)
}

func queryIANA(ctx context.Context, addr, tld string) (string, error) {
	dialer := net.Dialer{Timeout: 15 * time.Second}
	conn, err := dialer.DialContext(ctx, "tcp", addr)
	if err != nil {
		return "", err
	}
	defer func() { _ = conn.Close() }()

	if deadline, ok := ctx.Deadline(); ok {
		if err := conn.SetDeadline(deadline); err != nil {
			return "", err
		}
	} else if err := conn.SetDeadline(time.Now().Add(30 * time.Second)); err != nil {
		return "", err
	}

	if _, err := conn.Write([]byte(tld + "\r\n")); err != nil {
		return "", err
	}
	body, err := io.ReadAll(io.LimitReader(conn, 1<<20))
	if err != nil {
		return "", err
	}

	record := strings.ToLower(string(body))
	for _, line := range strings.Split(record, "\n") {
		rest, ok := strings.CutPrefix(strings.TrimSpace(line), "whois:")
		if !ok {
			continue
		}
		// A record with an empty whois: field is IANA saying the registry
		// publishes no WHOIS server, which is an answer, not a failure.
		return strings.TrimSpace(rest), nil
	}

	// No whois: line. Only a recognizably complete answer may be read as "this
	// TLD has no WHOIS server" — an empty or truncated response says nothing,
	// and taking it at face value would delete the entry from the table.
	if strings.Contains(record, "domain:") || strings.Contains(record, "this query returned 0 objects") {
		return "", nil
	}
	return "", fmt.Errorf("unrecognized response (%d bytes)", len(body))
}

// sortByURLThenKey orders one section's keys by server URL first, so entries
// for the same registry stay together and a registry migration shows up as one
// contiguous block in the diff instead of scattered lines.
func sortByURLThenKey(entries map[string]string) []string {
	keys := make([]string, 0, len(entries))
	for key := range entries {
		keys = append(keys, key)
	}
	sort.Slice(keys, func(i, j int) bool {
		if entries[keys[i]] != entries[keys[j]] {
			return entries[keys[i]] < entries[keys[j]]
		}
		return keys[i] < keys[j]
	})
	return keys
}

// writeGoFile gofmts src and writes it to path.
func writeGoFile(path string, src []byte) error {
	formatted, err := format.Source(src)
	if err != nil {
		return fmt.Errorf("%s: %w", path, err)
	}
	return os.WriteFile(path, formatted, 0o644)
}

// parseStringMap reads the named map[string]string variable out of a Go
// source file. A file that does not exist yet parses as an empty map.
func parseStringMap(path, name string) (map[string]string, error) {
	src, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return map[string]string{}, nil
	}
	if err != nil {
		return nil, err
	}

	file, err := parser.ParseFile(token.NewFileSet(), path, src, 0)
	if err != nil {
		return nil, err
	}
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.VAR {
			continue
		}
		for _, spec := range gen.Specs {
			value, ok := spec.(*ast.ValueSpec)
			if !ok || len(value.Names) != 1 || value.Names[0].Name != name || len(value.Values) != 1 {
				continue
			}
			lit, ok := value.Values[0].(*ast.CompositeLit)
			if !ok {
				return nil, fmt.Errorf("%s: %s is not a map literal", path, name)
			}
			entries := make(map[string]string, len(lit.Elts))
			for _, elt := range lit.Elts {
				kv, ok := elt.(*ast.KeyValueExpr)
				if !ok {
					continue
				}
				key, err := literalString(kv.Key)
				if err != nil {
					return nil, fmt.Errorf("%s: %w", path, err)
				}
				url, err := literalString(kv.Value)
				if err != nil {
					return nil, fmt.Errorf("%s: %w", path, err)
				}
				entries[key] = url
			}
			return entries, nil
		}
	}
	return nil, fmt.Errorf("%s: var %s not found", path, name)
}

func literalString(expr ast.Expr) (string, error) {
	lit, ok := expr.(*ast.BasicLit)
	if !ok || lit.Kind != token.STRING {
		return "", fmt.Errorf("expected a string literal, got %T", expr)
	}
	return strconv.Unquote(lit.Value)
}

// maxListed caps how many keys of one kind the summary spells out; monthly
// diffs are small, but a registry-wide migration is not.
const maxListed = 40

// writeDiff appends a per-file summary of what the run changed.
func writeDiff(summary *strings.Builder, file string, old, fresh map[string]string) {
	var added, removed, changed []string
	for key, url := range fresh {
		switch prev, ok := old[key]; {
		case !ok:
			added = append(added, fmt.Sprintf("`%s` → %s", key, url))
		case prev != url:
			changed = append(changed, fmt.Sprintf("`%s`: %s → %s", key, prev, url))
		}
	}
	for key, url := range old {
		if _, ok := fresh[key]; !ok {
			removed = append(removed, fmt.Sprintf("`%s` (was %s)", key, url))
		}
	}
	sort.Strings(added)
	sort.Strings(removed)
	sort.Strings(changed)

	fmt.Fprintf(summary, "### %s\n\n", file)
	if len(added)+len(removed)+len(changed) == 0 {
		fmt.Fprintf(summary, "Unchanged: %d entries.\n\n", len(fresh))
		return
	}
	fmt.Fprintf(summary, "%d entries (was %d): %d added, %d removed, %d changed.\n\n",
		len(fresh), len(old), len(added), len(removed), len(changed))
	writeList(summary, "Added", added)
	writeList(summary, "Removed", removed)
	writeList(summary, "Changed", changed)
}

func writeList(summary *strings.Builder, title string, items []string) {
	if len(items) == 0 {
		return
	}
	fmt.Fprintf(summary, "**%s**\n\n", title)
	for i, item := range items {
		if i == maxListed {
			fmt.Fprintf(summary, "- … and %d more\n", len(items)-maxListed)
			break
		}
		fmt.Fprintf(summary, "- %s\n", item)
	}
	summary.WriteString("\n")
}

// writeCollisions reports custom RDAP entries that IANA now publishes itself.
// Custom entries win over both the baseline and live IANA data, so a stale one
// keeps overriding the registry's own answer indefinitely.
func writeCollisions(summary *strings.Builder, custom, fresh map[string]string) bool {
	var redundant, conflicting []string
	for key, url := range custom {
		ianaURL, ok := fresh[key]
		switch {
		case !ok:
			continue
		case ianaURL == url:
			redundant = append(redundant, fmt.Sprintf("`%s` → %s", key, url))
		default:
			conflicting = append(conflicting, fmt.Sprintf("`%s`: custom %s overrides IANA %s", key, url, ianaURL))
		}
	}
	if len(redundant)+len(conflicting) == 0 {
		return false
	}
	sort.Strings(redundant)
	sort.Strings(conflicting)

	summary.WriteString("### ⚠️ rdap_servers_custom.go\n\n")
	summary.WriteString("IANA now publishes entries that are also listed as custom overrides. " +
		"Custom entries beat both the compiled baseline and live IANA data, so these need deleting by hand.\n\n")
	writeList(summary, "Now redundant", redundant)
	writeList(summary, "Overriding IANA with a different server", conflicting)
	return true
}
